responses:
  bot_error: "Возникла ошибка на стороне бота. Пожалуйста, попробуйте позже."
  bars:
    unavailable_pt: "Данные о Вашей успеваемости пока недоступны. Скорее всего они появятся позже."
    no_data_entered: "Данные для авторизации в БАРС не введены. Для авторизации введите /auth Логин Пароль."
    entry_form_ignored: "Данные введены не по форме. Для авторизации введите /auth Логин Пароль."
    data_entered_incorrectly: "Введённые данные некорректны. Для авторизации введите /auth Логин Пароль."
    default_answer: "Я понимаю только команды из списка: /help."

rabbitmq:
  consumer:
    telegram_messages: "telegram_messages"
    telegram_workers: 2
    grades_responses: "grades_responses"
    grades_workers: 1
    prefetch_count: 3

  producer:
    user_exchange: "user_exchange"
    auth_requests: "auth_requests"
    auth_requests_key: "auth_requests_key"
    logout_requests: "logout_requests"
    logout_requests_key: "logout_requests_key"
    news_requests: "news_requests"
    news_requests_key: "news_requests_key"
    delete_user_requests: "delete_user_requests"
    delete_user_requests_key: "delete_user_requests_key"
    grades_exchange: "grades_exchange"
    grades_requests: "grades_requests"
    grades_requests_key: "grades_requests_key"