version: '3.7'

services:
  tracking-bars:
    build: ./
    image: tracking-bars
    depends_on:
      postgres:
        condition: service_healthy
  postgres:
    restart: always
    image: postgres:13.3
    ports:
      - "5432:5432"
    environment:
      POSTGRES_HOST: localhost
      POSTGRES_DB: tracking-bars
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    healthcheck:
      test: ["CMD", "pg_isready"]
      interval: 5s
      timeout: 5s
      retries: 5