bars:
  urls:
    url: https://bars.mpei.ru/bars_web/
    registration_url: https://bars.mpei.ru/bars_web/
    main_page_url: https://bars.mpei.ru/bars_web/?sod=1

responses:
  bot_error: "Возникла ошибка на стороне бота. Пожалуйста, попробуйте позже."
  bars:
    error: "Ошибка авторизации. Не удалось обратиться к сервису БАРС."
    wrong_data: "Ошибка авторизации. Вероятно, введён неверный логин и/или пароль."
    not_authorized: "Вы не авторизованы в БАРС. Для авторизации введите: /auth Логин Пароль."
    already_authorized: "Вы уже авторизованы в БАРС. Для повторной авторизации введите /logout, затем /auth Логин Пароль."
    successful_authorization: "Авторизация в БАРС выполнена успешно. Теперь Вы будете получать уведомления об изменениях оценок."
    successful_logout: "Ваши данные успешно удалены. Для авторизации введите /auth Логин Пароль."

rabbitmq:
  consumer:
    news_requests: "news_requests"
    logout_requests: "logout_requests"
    auth_requests: "auth_requests"
    delete_user_requests: "delete_user_requests"
    news_workers: 1
    logout_workers: 1
    auth_workers: 1
    delete_user_workers: 1
    prefetch_count: 3
  producer:
    telegram_exchange: "telegram_exchange"
    telegram_messages: "telegram_messages"
    telegram_messages_key: "telegram_messages_key"