responses:
  bot_error: "Возникла ошибка на стороне бота. Пожалуйста, попробуйте позже."
  bars:
    error: "Ошибка авторизации. Не удалось обратиться к сервису БАРС."
    wrong_data: "Ошибка авторизации. Вероятно, введён неверный логин и/или пароль."
    expired_data: "Авторизационные данные устарели. Для отслеживания изменений оценок выполните авторизацию повторно. Возможно, возникла ошибка на сервере БАРС."
    not_authorized: "Вы не авторизованы в БАРС. Для авторизации введите: /auth Логин Пароль."
    unavailable_pt: "Данные о Вашей успеваемости пока недоступны. Скорее всего они появятся позже."
    no_data_entered: "Данные для авторизации в БАРС не введены. Для авторизации введите /auth Логин Пароль."
    entry_form_ignored: "Данные введены не по форме. Для авторизации введите /auth Логин Пароль."
    data_entered_incorrectly: "Введённые данные некорректны. Для авторизации введите /auth Логин Пароль."
    already_authorized: "Вы уже авторизованы в БАРС. Для повторной авторизации введите /logout, затем /auth Логин Пароль."
    successful_authorization: "Авторизация в БАРС выполнена успешно. Теперь Вы будете получать уведомления об изменениях оценок."
    successful_logout: "Ваши данные успешно удалены. Для авторизации введите /auth Логин Пароль."
    default_answer: "Я понимаю только команды из списка: /help."
bars:
  urls:
    url: https://bars.mpei.ru/bars_web/
    registration_url: https://bars.mpei.ru/bars_web/
    main_page_url: https://bars.mpei.ru/bars_web/?sod=1
  parser_delay_in_seconds: 600
