responses:
  bot_error: "Возникла ошибка на стороне бота. Пожалуйста, попробуйте позже."
  bars:
    expired_data: "Авторизационные данные устарели. Для отслеживания изменений оценок выполните авторизацию повторно. Возможно, возникла ошибка на сервере БАРС."
    not_authorized: "Вы не авторизованы в БАРС. Для авторизации введите: /auth Логин Пароль."
    default_answer: "Я понимаю только команды из списка: /help."
    pt_not_provided: "Ваши оценки не были получены, попробуйте позже или напишите обращение в поддержку бота."
    wrong_grades_page: "Бот не может получить Ваши оценки, воспользуйтесь командой /fixgrades для получения инструкции по исправлению ошибки."

bars:
  parser_delay_in_seconds:  600
  count_of_parsers: 5
  
rabbitmq:
  consumer:
    grades_requests: "grades_requests"
    grades_workers: 1
    prefetch_count: 3
  producer:
    telegram_exchange: "telegram_exchange"
    telegram_messages: "telegram_messages"
    telegram_messages_key: "telegram_messages_key"
    grades_responses: "grades_responses"
    grades_responses_key: "grades_responses_key"
